layout_spectrum: 0.7171870085557388
typography_spectrum: 0.9951522769891463
color:
  brandColors:
    - '#040507'
    - '#036f95'
    - '#fffdff'
    - '#58a2c9'
    - '#b99c7a'
  brandStrength: 0.4660996620357959
  lightness: 0.6798854903071787
  saturation: 0.8452398268599063
  rhythmicContrast: 0.07274489261671016
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: ''
author:
  name: Nicholas Rance
  email: nicholas.rance@gmail.com
name: Nick Rance
url: 'https://nickrance.com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Github
    url: 'https://github.com/NickRance'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/nicholas.rance'
    type: external
  - name: Twitter
    url: 'https://twitter.com/nick_rance'
    type: external
  - name: Portfolio
    id: 325ed09a-9ad3-41e9-b157-b835d110a6e7
    type: content
favicon: null
title: Nick's Site
content: []
description: Testing
purpose:
  - type: contact
    url: 'mailto:nicholas.rance@gmail.com'
    label: Contact me
