layout_spectrum: 0.2927684542041567
typography_spectrum: 0.9943213482563485
color:
  brandColors:
    - '#040507'
    - '#036f95'
    - '#fffdff'
    - '#58a2c9'
    - '#b99c7a'
  brandStrength: 0.009321720802713887
  lightness: 0.9127478112341227
  saturation: 0.7249669394006787
  rhythmicContrast: 0.4994076175228831
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: ''
name: Nick Rance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Github
    url: 'https://github.com/NickRance'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/nicholas.rance'
    type: external
  - name: Twitter
    url: 'https://twitter.com/nick_rance'
    type: external
favicon: null
title: Nick's Site
content: []
purpose:
  - type: contact
    url: 'mailto:nicholas.rance@gmail.com'
    label: Contact me
github: true
author:
  name: Nicholas Rance
  email: nicholas.rance@gmail.com
description: Testing
url: 'https://nickrance.com'
