name: Nick Rance
favicon: null
layout_spectrum: 0.23925
typography_spectrum: 1
title: "Nick's Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040507'
    - '#036f95'
    - '#fffdff'
    - '#58a2c9'
    - '#b99c7a'
  brandStrength: 0
  lightness: 0.3115386008284986
  saturation: 0.7264073072001338
  rhythmicContrast: 0.49635903094895184
purpose: []
